title: Data-analytiikka
description: Github pages testisivusto
theme: just-the-docs

url: https://data-analytiikka.github.io

aux_links:
  Lisämateriaalia: https://tilastoapu.wordpress.com/python

aux_links_new_tab: true

footer_content: "Kirjoittaja: Aki Taanila aki@taanila.fi"

search_enabled: false

callouts:
  highlight:
    color: yellow
  important:
    title: Tärkeää
    color: blue
  new:
    title: Harjoitus
    color: green
  note:
    title: Huomautus
    color: purple
  warning:
    title: Varoitus
    color: red
