title: Data-analytiikka
description: Github pages testisivusto
theme: just-the-docs

url: https://data-analytiikka.github.io

aux_links:
  Data-analytiikka Pythonilla: https://tilastoapu.wordpress.com/python

search_enabled: false
