title: Data-analytiikka
description: Github pages testisivusto
theme: just-the-docs
last_edit_time_format: "%Y-%m-%d"

url: https://data-analytiikka.github.io

aux_links:
  Lis채materiaalia: https://tilastoapu.wordpress.com/python

aux_links_new_tab: true

footer_content: "Kirjoittaja: Aki Taanila aki@taanila.fi"
last_edit_timestamp: true

search_enabled: false

callouts:
  highlight:
    color: yellow
  important:
    title: T채rke채채
    color: blue
  new:
    title: Harjoitus
    color: green
  note:
    title: Huomautus
    color: purple
  warning:
    title: Varoitus
    color: red
